//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessRole
    {
        public int id { get; set; }
        public string Section { get; set; }
        public bool CanEnter { get; set; }
        public bool CanCreate { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanDelete { get; set; }
        public Nullable<int> UserGroup_id { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
